"""Flask application for Authen — paid notarization over x402.

Three surfaces:

    GET  /health                free   liveness
    POST /api/v1/notarize       PAID   bytes -> signed attestation
    POST /api/v1/c2pa/sign      PAID   image -> C2PA Content Credentials embedded
    POST /api/v1/verify         free   attestation -> valid?  (drives discovery)
    POST /api/v1/c2pa/verify    free   image -> manifest + validation state
    GET  /api/v1/identity       free   this node's signing key + addresses

Verification is deliberately free. An attestation nobody can check is worth
nothing, so the cost of checking has to be zero — and a free verify endpoint is
what makes the paid one discoverable.

x402 is in the core flow, not bolted on: there is no unpaid path to an
attestation. That distinction is what judged criterion 2 measures.
"""

from __future__ import annotations

from flask import Flask, Response, jsonify, request
from x402.http.constants import (
    PAYMENT_REQUIRED_HEADER,
    PAYMENT_RESPONSE_HEADER,
    X_PAYMENT_RESPONSE_HEADER,
)
from x402.http.middleware.flask import payment_middleware
from x402.http.paywall import AvmPaywallHandler, PaywallBuilder

from ..config import NodeConfig, load_config
from ..keys import assert_identity, load_or_create
from ..c2pa_sign import SUPPORTED_FORMATS, build_app_ca, read_manifest, sign_image
from ..notary import build_attestation, sha256_hex, verify_attestation
from ..x402.server import build_server, routes_for

# Browser clients cannot read a response header unless it is explicitly exposed.
# v2 emits PAYMENT-RESPONSE; X-PAYMENT-RESPONSE is the v1 alias older clients want.
#
# PAYMENT-REQUIRED matters as much as the response headers and was missing: it
# carries the 402 challenge itself, so without it a browser-based payer can see a
# 402 and cannot read what it is being asked to pay. GoPlausible's x402 Doctor
# flags this.
#
# This constant only reaches responses Flask produces. The 402 is generated by
# payment_middleware in the WSGI layer OUTSIDE Flask, so `after_request` never
# runs for it and no amount of editing here will set a header on the challenge -
# which is exactly the response a browser payer needs to read. deploy/nginx
# sets it with `always` for that reason; see the note there.
_EXPOSE_HEADERS = (
    f"{PAYMENT_REQUIRED_HEADER}, {PAYMENT_RESPONSE_HEADER}, "
    f"{X_PAYMENT_RESPONSE_HEADER}, X-Authen-Attestation, X-Authen-CA-Fingerprint"
)

# A notarization request is a hash operation, not a storage service. Cap the body
# so one caller cannot pin a worker on a multi-gigabyte upload inside the payment
# window.
#
# There is no digest-submission mode: notarize() hashes whatever arrives, so a
# caller who sends a hex digest gets an attestation over that hex string. Do not
# reintroduce "send a digest for larger objects" as advice anywhere — it reads as
# a supported path and fails silently with a correct signature over the wrong
# thing. Building it for real means a distinct `i` value (the node observed a
# claim about bytes, not the bytes), which is a payload change, not a doc change.
#
# deploy/nginx/authen.conf must stay <= this number: nginx is what refuses an
# oversized body BEFORE the paywall. See the ordering note in that file.
#
# 48 MiB, not 32, and the gap is deliberate. This is Flask's MAX_CONTENT_LENGTH,
# which applies to EVERY route, so it has to clear the largest per-route cap nginx
# grants — and that is /api/v1/c2pa/verify at 48m, not the 32 MiB paid input cap.
# A C2PA-signed artifact is always larger than the bytes that produced it, so the
# free route that reads signed output must accept more than the paid route that
# produces it. Leave this at 32 and c2pa/verify 413s at 32 MiB no matter what
# nginx allows, because Flask is the stricter layer. See AUTHEN_API_REPORT.md §5.
#
# Raising this does NOT widen the paid routes: nginx still caps them at 32m, and
# nginx-stricter-than-Flask is the invariant that keeps the size check ahead of
# the paywall. tests/test_body_limits.py pins the whole ordering.
MAX_BODY_BYTES = 48 * 1024 * 1024


def create_app(cfg: NodeConfig | None = None) -> Flask:
    cfg = cfg or load_config()
    cfg.paths.ensure_dirs()

    identity = load_or_create(cfg.paths.data_dir)
    assert_identity(identity, cfg.identity_pubkey)

    # Built once at startup, not per request: the CA is deterministic in everything
    # but its serial number and validity window, and regenerating it per call would
    # change the fingerprint a trust registry recorded.
    app_ca = build_app_ca(identity, app_name=cfg.node_name)

    app = Flask(__name__)
    app.config["AUTHEN"] = cfg
    app.config["IDENTITY"] = identity
    app.config["MAX_CONTENT_LENGTH"] = MAX_BODY_BYTES

    # ---------------------------------------------------------------- free

    @app.get("/health")
    def health() -> Response:
        return jsonify(
            {
                "ok": True,
                "node": cfg.node_name,
                "network": cfg.network.name,
                "key": identity.public_hex,
            }
        )

    @app.get("/api/v1/identity")
    def node_identity() -> Response:
        """The key attestations are signed with, in every encoding it answers to.

        One Ed25519 key is simultaneously a Stellar and an Algorand address, which
        is what lets the same attestation be checked against a trust registry on
        either chain.
        """
        return jsonify(
            {
                "publicKey": identity.public_hex,
                "algorand": identity.algorand,
                "stellar": identity.stellar,
                "algorithm": "ed25519",
            }
        )

    @app.post("/api/v1/c2pa/verify")
    def c2pa_verify():
        """Free. Read an embedded C2PA manifest and report its validation state."""
        data = request.get_data(cache=False)
        if not data:
            return jsonify({"error": "empty body - send the image"}), 400
        media_type = (request.content_type or "").split(";")[0].strip()
        if media_type not in SUPPORTED_FORMATS:
            return jsonify(
                {
                    "error": f"unsupported Content-Type {media_type!r}",
                    "supported": sorted(SUPPORTED_FORMATS),
                }
            ), 415
        try:
            out = read_manifest(data, media_type)
        except Exception as exc:
            return jsonify({"embedded": False, "error": str(exc)[:200]}), 400
        return jsonify(out)

    @app.post("/api/v1/verify")
    def verify() -> Response:
        """Free. Checks an attestation is internally consistent and correctly signed.

        This does NOT decide whether the signing key deserves trust — that is the
        registry question, and conflating the two is how provenance claims get
        overstated.
        """
        body = request.get_json(silent=True) or {}
        wire = body.get("attestation") or request.get_data(as_text=True).strip()
        if not wire:
            return jsonify({"valid": False, "error": "no attestation supplied"}), 400

        ok, payload, error = verify_attestation(wire)
        out: dict = {"valid": ok, "payload": payload}
        if error:
            out["error"] = error
        if ok:
            out["signedBy"] = payload.get("k")
            out["knownKey"] = payload.get("k") == identity.public_hex
        return jsonify(out), (200 if ok else 400)

    # ---------------------------------------------------------------- paid

    @app.post("/api/v1/notarize")
    def notarize():
        """Hash the submitted bytes and return a signed, timestamped attestation.

        Reaching this handler means the middleware verified payment and will settle
        before any of this response is released to the caller.
        """
        data = request.get_data(cache=False)
        if not data:
            return jsonify({"error": "empty body — send the bytes to notarize"}), 400

        att = build_attestation(
            identity,
            digest_hex=sha256_hex(data),
            size=len(data),
            media_type=request.content_type or None,
        )
        return jsonify(
            {
                "statement": (
                    "This node observed bytes with the stated SHA-256 at the stated "
                    "time. It does not assert authorship, ownership, or prior existence."
                ),
                **att.to_dict(),
            }
        )

    @app.post("/api/v1/c2pa/sign")
    def c2pa_sign():
        """Embed signed C2PA Content Credentials into an image.

        Reaching this handler means payment verified and will settle before any of
        this response is released.
        """
        data = request.get_data(cache=False)
        if not data:
            return jsonify({"error": "empty body - send the image bytes"}), 400

        media_type = (request.content_type or "").split(";")[0].strip()
        if media_type not in SUPPORTED_FORMATS:
            return jsonify(
                {
                    "error": f"unsupported Content-Type {media_type!r}",
                    "supported": sorted(SUPPORTED_FORMATS),
                }
            ), 415

        att = build_attestation(
            identity,
            digest_hex=sha256_hex(data),
            size=len(data),
            media_type=media_type,
        )
        try:
            signed, chain = sign_image(
                identity, app_ca, data, media_type,
                claim_generator=cfg.node_name,
                attestation=att.to_dict(),
            )
        except Exception as exc:
            return jsonify({"error": f"signing failed: {str(exc)[:200]}"}), 400

        # The image is the payload; the attestation and CA fingerprint ride in
        # headers so a caller can check them without parsing the manifest.
        resp = Response(signed, mimetype=media_type)
        resp.headers["X-Authen-Attestation"] = att.wire
        resp.headers["X-Authen-CA-Fingerprint"] = chain.ca_fingerprint
        resp.headers["Content-Disposition"] = "attachment; filename=signed" + (
            SUPPORTED_FORMATS[media_type]
        )
        return resp

    @app.after_request
    def expose_payment_headers(resp: Response) -> Response:
        resp.headers.setdefault("Access-Control-Expose-Headers", _EXPOSE_HEADERS)
        return resp

    # x402 middleware last: it wraps the finished WSGI app.
    #
    # The paywall must be configured explicitly. With no provider the SDK serves its
    # EVM bundle, which parses our `algorand:` network id as an EVM chain id, throws
    # `Unsupported chain ID: NaN`, and renders a blank page. See tests/test_paywall.py.
    server = build_server(cfg)
    paywall = (
        PaywallBuilder()
        .with_network(AvmPaywallHandler())
        .with_config(app_name=cfg.node_name, testnet=cfg.network.name != "mainnet")
        .build()
    )
    payment_middleware(app, routes_for(cfg), server, paywall_provider=paywall)

    return app
